random_seed: 2024
environment_name: spotify
num_steps: 1.0e+5
num_eval: 101

agent_params:

    'pg':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {}

    'pg_hl_01':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .01}

    'pg_hl_02':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .02}

    'pg_hl_03':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .03}

    'pg_hl_04':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .04}

    'pg_hl_05':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .05}

    'pg_hl_06':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .06}

    'pg_hl_07':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .07}

    'pg_hl_08':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .08}

    'pg_hl_09':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .09}

    'pg_hl_10':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .10}

    'pg_hl_11':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .11}

    'pg_hl_12':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .12}

    'pg_hl_13':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .13}

    'pg_hl_14':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .14}

    'pg_hl_15':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .15}

