random_seed: 2024
environment_name: spotify
num_steps: 1.0e+5
num_eval: 101

agent_params:

    'pg':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {}

    'pg_mmd_01':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .01}

    'pg_mmd_02':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .02}

    'pg_mmd_03':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .03}

    'pg_mmd_04':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .04}

    'pg_mmd_05':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .05}

    'pg_mmd_06':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .06}

    'pg_mmd_07':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .07}

    'pg_mmd_08':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .08}

    'pg_mmd_09':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .09}

    'pg_mmd_10':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .10}

    'pg_mmd_11':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .11}

    'pg_mmd_12':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .12}

    'pg_mmd_13':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .13}

    'pg_mmd_14':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .14}

    'pg_mmd_15':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .15}

