random_seed: 2024
environment_name: cifar10
num_steps: 1.0e+6
num_eval: 101

agent_params:

    'pg':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {}

    'pg_hl_05':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .05}

    'pg_hl_10':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .10}

    'pg_hl_15':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .15}

    'pg_hl_20':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .20}

    'pg_hl_25':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .25}

    'pg_hl_30':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .30}

    'pg_hl_35':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .35}

    'pg_hl_40':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .40}

    'pg_hl_45':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .45}

    'pg_hl_50':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {hl: .50}


